### ISSUE TITLE
[Suggestion] Make any file includeable

### ISSUE THREAD

**Issue by Swader** [Webiny/Htpl#43]
You should be able to include any file, not just `.htpl` files. Sometimes, web components and similar helper elements are grabbed from other projects and they'll be `.html`. Being able to easily include those would be good.

If performance for file checking is a concern:
- first check if there is a variable with the name as defined in the `file` attribute
- if so, use variable. If not, look for file.

**Comment by SvenAlHamad** [comment]
Right, makes sense ... the only limitation that will be imposed is that the system will not allow including any files that contain PHP code.

Also, if the file contains `.htpl` extension, it will be parsed as a HTPL template, while any other file extension will just include the file content, without any parsing. 

Sounds good?

**Comment by Swader** [comment]
:+1 sounds great

**Comment by Swader** [comment]
@SvenAlHamad ping :P
